"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatcompletionstreamdelta import (
    ChatCompletionStreamDelta,
    ChatCompletionStreamDeltaTypedDict,
)
from pydantic import model_serializer
from r9s.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


ChatCompletionStreamChoiceFinishReason = Literal[
    "stop",
    "length",
    "tool_calls",
    "content_filter",
]


class ChatCompletionStreamChoiceLogprobsTypedDict(TypedDict):
    pass


class ChatCompletionStreamChoiceLogprobs(BaseModel):
    pass


class ChatCompletionStreamChoiceTypedDict(TypedDict):
    index: int
    delta: ChatCompletionStreamDeltaTypedDict
    finish_reason: NotRequired[Nullable[ChatCompletionStreamChoiceFinishReason]]
    logprobs: NotRequired[ChatCompletionStreamChoiceLogprobsTypedDict]


class ChatCompletionStreamChoice(BaseModel):
    index: int

    delta: ChatCompletionStreamDelta

    finish_reason: OptionalNullable[ChatCompletionStreamChoiceFinishReason] = UNSET

    logprobs: Optional[ChatCompletionStreamChoiceLogprobs] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["finish_reason", "logprobs"]
        nullable_fields = ["finish_reason"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
