"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "r9s"
__version__: str = "0.3.1"
__openapi_doc_version__: str = "0.1.0"
__gen_version__: str = "2.770.0"
__user_agent__: str = "speakeasy-sdk/python 0.3.1 2.770.0 0.1.0 r9s"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
